#!/usr/bin/env bash

APP_NAME={{.application}}
SERVICE_NAME={{.serviceName}}
#OPENSHIFT_CONSOLE_URL=Set to your OpenShift cluster's Console URL

SCRIPT_DIR=$(cd "$(dirname "$BASH_SOURCE")" ; pwd -P)
OPENSHIFTIO_DIR=${SCRIPT_DIR}/.openshiftio

case "$1" in
    "deploy")
        PARAMS=""
        REPO_URL=$(git config --get remote.origin.url || echo "")
        if [[ ! -z "${REPO_URL}" ]]; then
            PARAMS="$PARAMS -p=SOURCE_REPOSITORY_URL=${REPO_URL}"
        fi
        if [[ ! -z "${OPENSHIFT_CONSOLE_URL}" ]]; then
            PARAMS="$PARAMS -p=OPENSHIFT_CONSOLE_URL=${OPENSHIFT_CONSOLE_URL}"
        fi
        if [[ -f ${OPENSHIFTIO_DIR}/application.yaml ]]; then
            oc process -f ${OPENSHIFTIO_DIR}/application.yaml --ignore-unknown-parameters ${PARAMS} | oc apply -f -
        fi
        if [[ -f ${OPENSHIFTIO_DIR}/service.welcome.yaml ]]; then
             oc process -f ${OPENSHIFTIO_DIR}/service.welcome.yaml --ignore-unknown-parameters ${PARAMS} | oc apply -f -
        fi
        ;;
    "build")
        ;;
    "push")
        ;;
    "delete")
        oc delete all,secrets -l app=${APP_NAME}
        ;;
    *)
        echo "Usage: gap [deploy|push|delete] ..."
        echo "   deploy  - Deploys the application to OpenShift"
        echo "   delete  - Deletes the application from OpenShift"
    ;;
esac
