FROM registry.access.redhat.com/rhoar-nodejs/nodejs-10:latest

MAINTAINER Fabric8 Launcher Team <fabric8-launcher@googlegroups.com>

LABEL maintainer "Fabric8 Launcher Team <fabric8-launcher@googlegroups.com>"
LABEL author "Fabric8 Launcher Team <fabric8-launcher@googlegroups.com>"

ENV LANG=en_US.utf8

COPY node_modules /opt/app-root/src/node_modules/
COPY dist /opt/app-root/src/dist/
COPY package.json /opt/app-root/src/
COPY openapi.yaml /opt/app-root/src/

CMD ${STI_SCRIPTS_PATH}/run