FROM registry.access.redhat.com/rhoar-nodejs/nodejs-10:latest

MAINTAINER Fabric8 Launcher Team <fabric8-launcher@googlegroups.com>

LABEL maintainer "Fabric8 Launcher Team <fabric8-launcher@googlegroups.com>"
LABEL author "Fabric8 Launcher Team <fabric8-launcher@googlegroups.com>"

ENV LANG=en_US.utf8

WORKDIR /opt/app-root

COPY node_modules /opt/app-root/node_modules/
COPY dist /opt/app-root/dist/
COPY *.json /opt/app-root/
COPY *.yaml /opt/app-root/

CMD ${STI_SCRIPTS_PATH}/run