#!/bin/bash

SOURCE_DIR=$(cd "$(dirname "$BASH_SOURCE")" ; pwd -P)

set -a
source $SOURCE_DIR/env
set +a

# Create a Secret holding the DB connection information
if ! oc get secret ${SECRET_NAME} | grep ${SECRET_NAME}; then
    oc create secret generic ${SECRET_NAME} \
        --from-literal=uri=${DB_NAME} \
        --from-literal=user=dbuser \
        --from-literal=password=secret
fi

# Create the PostgreSQL DB service
USRENV='{"name":"POSTGRESQL_USER","valueFrom":{"secretKeyRef":{"name":"'${SECRET_NAME}'","key":"user"}}}'
PWDENV='{"name":"POSTGRESQL_PASSWORD","valueFrom":{"secretKeyRef":{"name":"'${SECRET_NAME}'","key":"password"}}}'
QUERY='(.items[] | select(.kind == "DeploymentConfig") | .spec.template.spec.containers[0].env)'
if ! oc get service ${DB_NAME} | grep ${DB_NAME}; then
    oc new-app \
        --name=${DB_NAME} \
        -ePOSTGRESQL_DATABASE=my_data \
        postgresql \
        --dry-run \
        -o json | \
        jq "$QUERY += [$USRENV,$PWDENV]" | \
        oc apply -f -
fi

