# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1
orbs:
  ike: bartoszmajsak/ike@0.0.1
jobs:
  build:
    docker:
      - image: circleci/node:10-browsers

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: yarn test

  e2e_tests:
    machine:
      image: circleci/classic:201808-01
    steps:
      - checkout
      - ike/docker_insecure_registry
      - ike/install_maistra
      - run: sudo -H -i -u circleci nvm install 10.10

#
#          name: Update BASH_ENV
#          commands: |
#           echo 'export NVM_DIR=$HOME/.nvm' >> $BASH_ENV
#           echo 'source $NVM_DIR/nvm.sh' >> $BASH_ENV
#           source $BASH_ENV
      - run: sudo -H -i -u circleci npm install yarn -g
      - run: sudo -H -i -u circleci yarn install
      - run: oc cluster up
      - run: sudo -H -i -u circleci yarn itests


workflows:
  version: 2.1
  circleci_build:
    jobs:
      - build
  circleci_e2e_tests:
    jobs:
      - e2e_tests
