apiVersion: v1
kind: Template
parameters:
- name: APP_NAME
  description: The name for the application
  displayName: Application Name
  required: true
- name: WELCOME_APP_CONFIG
  description: The configuration for the welcome app
  displayName: Welcome App Configuration
  required: true
- name: BACKEND_SERVICE_NAME
  description: The backend service name for the welcome app
  displayName: Backend service name
  required: true
- name: SOURCE_REPOSITORY_PROVIDER
  description: The source repository provider
  displayName: Source Provider
  value: GitHub
- name: SOURCE_REPOSITORY_URL
  description: The source URL for the application
  displayName: Source URL
- name: OPENSHIFT_CONSOLE_URL
  description: The OpenShift Console URL for the application
  displayName: OpenShift Console URL
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: launcher-welcome-app
    labels:
      app: ${APP_NAME}
      apptype: welcome
  spec:
    lookupPolicy:
      local: false
    tags:
    - name: latest
      from:
        kind: DockerImage
        name: fabric8/launcher-creator-welcome-app
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: launcher-welcome-app
    labels:
      app: ${APP_NAME}
      apptype: welcome
  spec:
    replicas: 1
    selector:
      app: ${APP_NAME}
      deploymentconfig: launcher-welcome-app
    strategy:
      resources: {}
    template:
      metadata:
        labels:
          app: ${APP_NAME}
          deploymentconfig: launcher-welcome-app
      spec:
        containers:
        - image: fabric8/launcher-creator-welcome-app
          name: launcher-welcome-app
          ports:
          - containerPort: 8080
            protocol: TCP
          resources: {}
          env:
            - name: WELCOME_APP_CONFIG
              value: '${WELCOME_APP_CONFIG}'
            - name: OPENSHIFT_CONSOLE_URL
              value: '${OPENSHIFT_CONSOLE_URL}'
            - name: SOURCE_REPOSITORY_PROVIDER
              value: '${SOURCE_REPOSITORY_PROVIDER}'
            - name: SOURCE_REPOSITORY_URL
              value: '${SOURCE_REPOSITORY_URL}'
            - name: BACKEND_SERVICE_NAME
              value: '${BACKEND_SERVICE_NAME}'
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - launcher-welcome-app
        from:
          kind: ImageStreamTag
          name: launcher-welcome-app:latest
      type: ImageChange
  status:
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    updatedReplicas: 0
    availableReplicas: 0
    unavailableReplicas: 0
- kind: Service
  apiVersion: v1
  metadata:
    name: launcher-welcome-app
    labels:
      app: ${APP_NAME}
      apptype: welcome
  spec:
    ports:
    - name: 8080-tcp
      protocol: TCP
      port: 8080
      targetPort: 8080
    selector:
      app: ${APP_NAME}
      deploymentconfig: launcher-welcome-app
- apiVersion: v1
  kind: Route
  metadata:
    name: launcher-welcome-app
    labels:
      app: ${APP_NAME}
      apptype: welcome
    annotations:
      console.alpha.openshift.io/overview-app-route: 'true'
  spec:
    port:
      targetPort: 8080-tcp
    to:
      kind: Service
      name: launcher-welcome-app
