#!/usr/bin/env bash

APP_NAME={{.application}}
SERVICE_NAME={{.serviceName}}
JAR_NAME={{.maven.artifactId}}-{{.maven.version}}.jar
#OPENSHIFT_CONSOLE_URL=Set to your OpenShift cluster's Console URL

SCRIPT_DIR=$(cd "$(dirname "$BASH_SOURCE")" ; pwd -P)
OPENSHIFTIO_DIR=${SCRIPT_DIR}/.openshiftio
SOURCE_DIR=${SCRIPT_DIR}
if [[ ! -z "{{.tier}}" ]]; then
    SOURCE_DIR=${SOURCE_DIR}/..
    TIER_DIR=/{{.tier}}
fi

while [[ $# > 0 ]]; do
    CMD=$1
    shift
    case "$CMD" in
        "deploy")
            PARAMS=""
            REPO_URL=$(git config --get remote.origin.url || echo "")
            if [[ ! -z "${REPO_URL}" ]]; then
                PARAMS="$PARAMS -p=SOURCE_REPOSITORY_URL=${REPO_URL}"
            fi
            if [[ ! -z "${OPENSHIFT_CONSOLE_URL}" ]]; then
                PARAMS="$PARAMS -p=OPENSHIFT_CONSOLE_URL=${OPENSHIFT_CONSOLE_URL}"
            fi
            oc process -f ${OPENSHIFTIO_DIR}/application.yaml --ignore-unknown-parameters ${PARAMS} | oc apply -f -
            if [[ -f ${OPENSHIFTIO_DIR}/service.welcome.yaml ]]; then
                 oc process -f ${OPENSHIFTIO_DIR}/service.welcome.yaml --ignore-unknown-parameters ${PARAMS} | oc apply -f -
            fi
            ;;
        "build")
            mvn package
            ;;
        "clean")
            mvn clean
            ;;
        "push")
            BINARY=${SCRIPT_DIR}/target/${JAR_NAME}
            if [[ "$1" == "--binary" || "$1" == "-b" ]]; then
                shift
                FROM=${SCRIPT_DIR}/target/_oc_build_tmp_
                mkdir -p ${FROM}${TIER_DIR}
                cp ${BINARY} ${FROM}${TIER_DIR}
                oc start-build ${SERVICE_NAME} --from-dir ${FROM} "$@"
                rm -rf ${FROM}
            elif [[ "$1" == "--source" || "$1" == "-s" ]]; then
                shift
                oc start-build ${SERVICE_NAME} --from-dir ${SOURCE_DIR} "$@"
            elif [[ "$1" == "--git" || "$1" == "-g" ]]; then
                shift
                oc start-build ${SERVICE_NAME} "$@"
            else
                if [[ -f ${BINARY} ]]; then
                    FROM=${SCRIPT_DIR}/target/_oc_build_tmp_
                    mkdir -p ${FROM}${TIER_DIR}
                    cp ${BINARY} ${FROM}${TIER_DIR}
                    oc start-build ${SERVICE_NAME} --from-dir ${FROM} "$@"
                    rm -rf ${FROM}
                else
                    oc start-build ${SERVICE_NAME} --from-dir ${SOURCE_DIR} "$@"
                fi
            fi
            ;;
        "delete")
            oc delete all,secrets -l app=${APP_NAME}
            ;;
        *)
            echo "Usage: gap [deploy|build|clean|push|delete] ..."
            echo "   deploy  - Deploys the application to OpenShift"
            echo "   build   - Builds the application from code"
            echo "   clean   - Cleans any build artifacts"
            echo "   push    - Pushes code to the application. By default this will push the pe-compiled"
            echo "             binary if it exists, otherwise it will push the local sources to be compiled"
            echo "             on OpenShift. This can be overridden by using one of the following flags:"
            echo "      -b, --binary - Pushes a pre-compiled binary"
            echo "      -s, --source - Pushes the sources"
            echo "      -g, --git    - Reverts to using the sources from Git"
            echo "   delete  - Deletes the application from OpenShift"
        ;;
    esac
done
